spring.application.name=budget
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Budget
spring.datasource.password=budget#=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

