spring.application.name=budget
spring.datasource.url=jdbc:h2:file:./data/personal-finances
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Budget
spring.datasource.password=budget#=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
apring.h2.console.path=/h2-console