create table transactions
(
    id        bigint generated by default as identity primary key,
    amount    numeric(19, 2) not null,
    category  varchar(255)   not null check (category in (
                                                          'HABITATION',
                                                          'TRANSPORT',
                                                          'HEALTH',
                                                          'ENTERTAINMENT',
                                                          'FOOD',
                                                          'EDUCATION',
                                                          'MAINTENANCE',
                                                          'OTHER',
                                                          'SALARY'
        )),
    timestamp timestamp(6)   not null,
    type      varchar(255)   not null check (type in (
                                                      'INCOME',
                                                      'EXPENSE'
        ))
);